### ISSUE TITLE
Log Set rollover bug

### ISSUE THREAD

**Issue by guywithaview** [mongoose-os-libs/file-logger#2]
https://github.com/mongoose-os-libs/file-logger/blob/a1964ec96df5c399a3a8b3198ca1e809239e25ad/src/mgos_file_logger.c#L53

I think this line should be `if (s_seq < max_seq) {`

From testing mine, it looks like `s_seq` seems to actually hit 100 which messes up the filename eg: log_**1100**-20200729-053643.log
This then messes up the oldest/newest file detection.

Happy to be proven wrong. Love the library otherwise!

**Comment by rojer** [comment]
no, it has to be 100 because we only allocate 2 digits for the sequence, the third digit is log set that goes 0, 1 and 2.
i remember spending quite a bit of time on this, precisely to ensure we always keep the right number of files around from oldest to newest.
with file_logger.max_num_files = 10 files will not go from 000 to 009 and back, they will actually go 000, ..., 009, 100, ..., 109, 200, ..., 209, 000, ...
this is why file_logger.max_num_files cannot be greater than 100. s_seq should not hit 100, assuming the conditional statement works correctly.

**Comment by guywithaview** [comment]
Ahh apologies, I think I've made a problem for myself by sending & deleting the completed log files as soon as their made. So other bits of code are expecting to hit max_num_files first, rather than s_seq actually hitting 100 because there are no other files to count.
Thanks for the quick response, I'll fix up my local version.
